[project]
name = "tonic-ollama-client"
version = "0.1.0"
description = "A very simple ollama client for our tonic software."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ollama>=0.5.1",
    "rich>=14.0.0",
    "tenacity>=9.1.2",
]
